# Generated by Django 5.0.6 on 2025-08-13 20:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Tienda')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del Logo de la Tienda')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('dias_atencion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Días y horarios de atención')),
                ('tiene_delivery', models.BooleanField(default=False, verbose_name='Ofrece servicio de Delivery')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Repuesto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('marca_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca del vehículo')),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo del vehículo')),
                ('anio_vehiculo', models.IntegerField(blank=True, null=True, verbose_name='Año del vehículo')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de la Imagen')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buscador.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Repuesto Global',
                'verbose_name_plural': 'Repuestos Globales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(help_text='Punto geográfico de la sucursal.', srid=4326, verbose_name='Ubicación (Lat, Lng)')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='buscador.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['tienda', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo', 'anio'],
                'unique_together': {('marca', 'modelo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='RepuestoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('repuesto_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.repuestoglobal', verbose_name='Repuesto Global')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Repuesto por Sucursal',
                'verbose_name_plural': 'Repuestos por Sucursal',
                'unique_together': {('sucursal', 'repuesto_global')},
            },
        ),
    ]
