# Generated by Django 5.2.5 on 2025-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuestoglobal',
            name='anio_vehiculo',
        ),
        migrations.RemoveField(
            model_name='repuestoglobal',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='repuestoglobal',
            name='marca_vehiculo',
        ),
        migrations.RemoveField(
            model_name='repuestoglobal',
            name='modelo_vehiculo',
        ),
        migrations.AddField(
            model_name='repuestoglobal',
            name='compatibilidad',
            field=models.ManyToManyField(related_name='repuestos_compatibles', to='buscador.vehiculo', verbose_name='Vehículos compatibles'),
        ),
    ]
