"""
Django settings for sisrep_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5w@22xco1z@q%j9))@1uce7jl94ohnw&3e%h-hz=vgsc@yr!$y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'leaflet',
    'easy_thumbnails',
    'multiselectfield',
    'locations',
    'users',  # Agrega esta línea
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sisrep_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'easy_thumbnails.templatetags.thumbnail',
            ],
        },
    },
]

WSGI_APPLICATION = 'sisrep_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'sisrep_db',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---
# CONFIGURACIÓN GIS Y MAPAS
# ---

# Las librerías GDAL y GEOS se instalaron en tu nuevo entorno `sisrep-stable-env`.
# Por lo tanto, las rutas deben apuntar a ese directorio.
os.environ['PROJ_LIB'] = r'C:\Users\carlosdev\miniconda3\envs\sisrep-stable-env\Library\share\proj'
os.environ['GDAL_LIBRARY_PATH'] = r'C:\Users\carlosdev\miniconda3\envs\sisrep-stable-env\Library\bin\gdal307.dll'
os.environ['GEOS_LIBRARY_PATH'] = r'C:\Users\carlosdev\miniconda3\envs\sisrep-stable-env\Library\bin\geos_c.dll'

# Configuración de Django-Leaflet para el mapa del panel de administración
LEAFLET_CONFIG = {
    # Coordenadas de latitud y longitud para el centro del mapa
    'DEFAULT_CENTER': (-23.4425, -58.4438),  # (Latitud, Longitud)
    # Nivel de zoom predeterminado
    'DEFAULT_ZOOM': 6,
    # Nivel de zoom mínimo y máximo
    'MIN_ZOOM': 2,
    'MAX_ZOOM': 18,
    # Capa de mapa base
    'DEFAULT_TILE_LAYER': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    # Atribución para la capa de mapa
    'ATTRIBUTION_PREFIX': 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}

# ---
# CONFIGURACIÓN DE ARCHIVOS MULTIMEDIA
# ---
# Directorio donde se guardarán los archivos multimedia
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

THUMBNAIL_ALIASES = {
    '': {
        'logo_list': {'size': (96, 96), 'crop': True, 'upscale': False},
        'logo_detail': {'size': (100, 100), 'crop': True, 'upscale': False},
    },
}