# Generated by Django 5.0.6 on 2025-08-12 22:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import easy_thumbnails.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Tiene Delivery')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=100, verbose_name='Días de Atención')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('part_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Parte')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=100, verbose_name='Nombre del Taller')),
                ('head_mechanic_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Jefe de Taller')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Número de Contacto')),
                ('service_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MECANICA', 'Mecánica'), ('CHAPERIA', 'Chapería'), ('PINTURA', 'Pintura'), ('ELECTRICIDAD', 'Electricidad')], max_length=38, verbose_name='Tipo de Servicio')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='professional_logos/', verbose_name='Logotipo')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=100, verbose_name='Días de Atención')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Tienda')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=100, verbose_name='Días de Atención')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='branch_images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='professional_images/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.branch', verbose_name='Sucursal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.product', verbose_name='Producto')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.store', verbose_name='Tienda Matriz'),
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='store_images/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.store')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('branch__isnull', False), ('store__isnull', True)), models.Q(('branch__isnull', True), ('store__isnull', False)), _connector='OR'), name='one_location_type_for_stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('branch', 'product'), ('store', 'product')},
        ),
    ]
