# Generated by Django 5.2.5 on 2025-08-11 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=200, verbose_name='Nombre del Taller/Empresa')),
                ('head_mechanic_name', models.CharField(max_length=100, verbose_name='Nombre del Profesional')),
                ('service_type', models.CharField(choices=[('Taller', 'Taller'), ('Autoeléctrica', 'Autoeléctrica'), ('Tornería', 'Tornería'), ('Gomería', 'Gomería'), ('Chapería y Pintura', 'Chapería y Pintura'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Servicio')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Días y Horarios de Trabajo')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación GPS')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Es Anuncio Destacado')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Tienda')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación GPS')),
            ],
            options={
                'verbose_name': 'Tienda Principal',
                'verbose_name_plural': 'Tiendas Principales',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Sucursal')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación GPS')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Ofrece Delivery')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.store', verbose_name='Tienda Principal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
